### ISSUE TITLE
Rough Roadmap

### ISSUE THREAD

**Issue by ParzivalWolfram** [linux-3ds/linux#94]
At current, it appears I'm the last person monitoring the repos, and as such, I'm going to attempt to shore this up with my extremely limited knowledge and abilities once one of my other large projects is finished. As such, a rough outline of higher-priority tasks are below:

- [ ] Get generic SDIO driver up and running, probably move SD/WiFi drivers to userland so bugs in those don't crash the kernel as easily?
- [ ] Make generic ARM9-to-ARM11 interface for arbitrary read/write
- [ ] Add working SPI support, probably only useful for serial communication with a PC over NDSCARD at current (though this _would_ make development way faster since i'd be able to bypass the touch keyboard)
- [ ] 2D acceleration, maybe? I'm not anywhere close to knowledgeable enough to get 3D accel working, especially not a full OpenGL/Vulkan implementation...

**Comment by ds84182** [comment]
OpenGLES 1.1 support should technically be possible since DMP made the PICA200 with ES 1.1 support in mind.

For WiFi, I tried hosting nwm in userspace. The driver worked enough to talk to the wifi chip however I wasn't able to get DMA working. May consider trying udmabuf to ensure the buffers are contiguous. For performance I'd have to rewrite it to take advantage of [syscall user dispatch](https://docs.kernel.org/admin-guide/syscall-user-dispatch.html) which was added in 5.11.

**Comment by ParzivalWolfram** [comment]
> For WiFi, I tried hosting nwm in userspace. The driver worked enough to talk to the wifi chip however I wasn't able to get DMA working. May consider trying udmabuf to ensure the buffers are contiguous. For performance I'd have to rewrite it to take advantage of [syscall user dispatch](https://docs.kernel.org/admin-guide/syscall-user-dispatch.html) which was added in 5.11.

I've been attempting to get ath6kl to work with it, since it has a generic board option, but the current issue is SDIO/SDHC support overall. There aren't many drivers that work outside of PCI/USB readers, and it's been infuriating trying to get toshsd working (mainly due to lack of C knowledge and free time on my part.)

**Comment by ItsCOMMANDer** [comment]
Any updates?

**Comment by ParzivalWolfram** [comment]
> Any updates?

Not currently. I've been having real-life issues crop up constantly, and i'm finishing up another project at the request of a friend.

**Comment by ParzivalWolfram** [comment]
Upon further inspection, ath6kl can't seem to use the generic board mode on this flavor of ath6 hardware, and the System Menu's firmware blobs are worthless as well (they all expose a custom interface, and are generally not helpful unless I learn assembly for the Xtensa architecture and make them conformant, which is beyond me currently.) 

My test unit also spontaneously lost the ability to accept touch input (Y axis is correct, X axis is dead center of the screen no matter what) so i'm going to need to acquire a new unit to either repair or replace my current one, which is increasingly expensive.
